spring.application.name=placement-tracker
spring.datasource.url=jdbc:mysql://localhost:3306/placement_tracker
spring.datasource.username=root
spring.datasource.password=Soniya@22

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true